Added 6 new internships
jenndryden/Canadian-Tech-Internships-Summer-2024 pull request #87
Opened 2023-08-05 06:02 UTC by ShevinuM

2023-08-05 16:44 UTC, kanjurer commented
The Autodesk one does not seem to be for Summer 2024.

2023-08-05 16:46 UTC, kanjurer commented
Also for the Waabi one, https://jobs.lever.co/waabi/ad3c77da-5607-4c4f-8784-8407478cbace this might be a better link to put.

2023-08-05 17:28 UTC, ShevinuM commented
> The Autodesk and Perpetua ones do not seem to be for Summer 2024. They are for Fall 2023, correct me if I am wrong
> 
> 

It is actually once you click and apply now. But I'll update the link to the workday one instead of that

2023-08-05 17:29 UTC, ShevinuM commented
> Also for the Waabi one, https://jobs.lever.co/waabi/ad3c77da-5607-4c4f-8784-8407478cbace this might be a better link to put.
> 
> For Klue, https://jobs.lever.co/klue/b88e45c3-c067-410b-a7d3-ca23142b9bef link is better

I will make the changes

2023-08-05 18:23 UTC, ShevinuM commented
> The Autodesk and Perpetua ones do not seem to be for Summer 2024. They are for Fall 2023, correct me if I am wrong

This was a mistake on my behalf. The internship starts early spans to Summer 24.

2023-08-05 18:28 UTC, ShevinuM commented
Two of the internships have closed and I removed them. So there's still 2 active internships remaining which is in the list.

2023-08-05 20:21 UTC, kanjurer requested changes

2023-08-05 20:21 UTC, kanjurer commented on README.md
> +| [Waabi](https://jobs.lever.co/waabi/ad3c77da-5607-4c4f-8784-8407478cbace)                           | Toronto, ON, Canada           | Unknown              | Research Internship/Co-op
Nit: Indentation is a bit off. Could copy pasta this:

```
| [Waabi](https://jobs.lever.co/waabi/ad3c77da-5607-4c4f-8784-8407478cbace)                                                | Toronto, ON, Canada           | Unknown              | Research Internship/Co-op                                       |
| [Klue](https://jobs.lever.co/klue/b88e45c3-c067-410b-a7d3-ca23142b9bef)                                                  | Unknown                       | Unknown              | Data Analyst Intern                                             |
```

2023-08-05 20:21 UTC, kanjurer commented on README.md
> +| [Klue](https://jobs.lever.co/klue/b88e45c3-c067-410b-a7d3-ca23142b9bef)                                  | Unknown                      | Unknown              | Data Analyst Intern
You can use prettier (or some sort of linter) in VS Code to do the linting for you. Makes it less troublesome 😓

2023-08-06 12:24 UTC, ShevinuM commented on README.md
>  | [Intuit](https://jobs.intuit.com/search-jobs/Toronto%2C%20Canada/27595/4/6251999-6093943-6167865/43x70011/-79x4163/50/2) | Toronto                       | Unknown              | Software Developer
https://waabi.ai
https://klue.com/careers

You could visit the websites and checkout. They redirect you to the lever website which I why it's not the company website that's included.

2023-08-06 12:35 UTC, ShevinuM commented
I've made the changes requested. Also there is no 'company' link for the posting because it's the company itself who directs you to that link.

2023-08-06 19:25 UTC, jenndryden approved these changes
this looks great!

2023-08-06 19:26 UTC, merged